### ISSUE TITLE
Minipileup algorithm

### ISSUE THREAD

**Issue by saassli21** [lh3/minipileup#10]
Good morning,

First I want to thank you for this wonderful tool.
In fact, I am particularly interested in understanding the algorithm behind Minipileup. While I have reviewed your response on issue #9 , 
I find myself needing a bit more detail to fully grasp how it operates. 
Could you please provide a more in-depth explanation of the Minipileup algorithm? 

Thank you very much for your time

**Comment by lh3** [comment]
It just counts bases. Nothing special. But if you want to "fully grasp how it operates", I am afraid you will have to read code.

**Comment by saassli21** [comment]
> It just counts bases. Nothing special. But if you want to "fully grasp how it operates", I am afraid you will have to read code.

@ it's a pairwise comparison ? like a blastn ?
