### ISSUE TITLE
Extraction of information from VCF file

### ISSUE THREAD

**Issue by QuentinPerriere** [lh3/minipileup#7]
**Thank you for providing this wonderful tool.** 
As a beginner, I am still struggling to comprehend the structure of the VCF file. I executed the following command: 

**./minipileup -vcC -a 1 -f /lab/user/ref_bioedit.fa /lab/user/bam_file.dedup.bam > var.vcf.** 

Now, I am wondering how to interpret the variants listed in the example: 
**Aga 928 . C A,G,T 161 . . GT:ADF:ADR 3/0:18,2,3,73:18,1,6,88.** 
I **already** know that the exact variant is (ref: C and alt: T). 
    - How can I filter out insignificant substitutions or insertions and display only the relevant ones?
    -  Additionally, how can I determine the number of reads supporting a variant per sample?
    -  final question is there a way to add a tag in order to know the type of variant ( snp , insertion , deletion ? )

**Comment by QuentinPerriere** [comment]
@lh3 could you please help me with this !!!

**Comment by lh3** [comment]
I am afraid that you will have to write a script. You can also try bcftools but I am not sure if it can do the job for you.
