### ISSUE TITLE
utilities

### ISSUE THREAD

**Issue by SueFletcher** [lh3/minipileup#9]
Hello,

I have a question regarding the utility of minipileup: Is it suitable for both short and long reads, or is it primarily desired for short reads? Additionally, I am curious if there are any published articles discussing minipileup that you would recommend. 

Thank you in advance for your assistance. I truly appreciate the hard work and dedication of the developers who contribute to tools like minipileup.

**Comment by lh3** [comment]
Minipileup works with both short and long reads. It simply counts alleles; no complex algorithms involved.
